### ISSUE TITLE
Please provide groups access to parsys_test@mozilla.com

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/sso-dashboard#100]
As per last topic in [https://docs.google.com/document/d/1mWqtK-Bz9YXr0jl4KzqBJqJ7mq1wFQRXBvZykUWap40/edit](https://docs.google.com/document/d/1mWqtK-Bz9YXr0jl4KzqBJqJ7mq1wFQRXBvZykUWap40/edit),  I would like to have my test user (parsys_test@mozilla.com) added to the groups from the table, so that I can test the access to those apps from the dashboard. 
@jdow , can you provision these groups for my test user? Thanks!

**Comment by jdow** [comment]
First, my apologies for not seeing this sooner. I think the short answer here is "probably not". Some of those RPs have meanwhile been decomissioned, others actually have some internal user management, so adding to the group would not actually grant access to the RPs anyway, others are relatively sensitive groups that would grant other power, likely not appropriate for the test user, and others are not actually managed by IT, or would need individual ack from various business owners.

It is possible that we just add the parsys_test user into the authorized_users section for each item in the dashboard config, which will enable the icon to show up for RPs that have display set to true, but as of now, it wouldn't necessarily grant any access to the RPs themselves, and would likely result in lots of false "I see the icon, but can't access the RP" type of bugs.

If this is absolutely needed, then we'll need to work with each individual RP owner (for the ones that aren't deprecated) to find out if we have permission to grant this user access to the RPs.
