### ISSUE TITLE
App icons and app page requires scrolling, even on high-DPI monitors

### ISSUE THREAD

**Issue by deadsquid** [mozilla-iam/sso-dashboard#101]
After logging into SSO, the new apps page requires scrolling even on high DPI monitors. The App icons are quite large, and viewing all of them requires scrolling through 3.5 pages in a normal-sized window. Can we reduce the apps so they fit on a single page, as they were before? 

![sso](https://cloud.githubusercontent.com/assets/2007685/25629698/758aaf64-2f38-11e7-94e4-40d1fbccfa8c.jpg)

**Comment by m-branson** [comment]
@deadsquid thanks for the issue submit, we're working on an update. 👍

**Comment by deadsquid** [comment]
Awesome. Nice turnaround!!!

**Comment by m-branson** [comment]
Thanks @deadsquid -- really appreciate your input, keep it coming!
