### ISSUE TITLE
Can't re-order apps in SSO view

### ISSUE THREAD

**Issue by deadsquid** [mozilla-iam/sso-dashboard#104]
Given issue #101 I'd like to be able to re-order app icons so that the apps I access frequently from the SSO page are above the fold. Ideally there'd be a simple ordering mechanism for pages (and sub-pages), but it's not clear if that is an option. As a feature enhancement, I'd like to be able to set the order Apps appear in.

**Comment by andrewkrug** [comment]
This is on our roadmap for future currently.

**Comment by dividehex** [comment]
This is no longer on the roadmap.

**Comment by deadsquid** [comment]
Harsh. 😂
