### ISSUE TITLE
Run access-proxy in front of SSO dashboard

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#107]
As discussed, to properly fix the session management (current hardcoded to 24h session cookies) the best solution we though of is to run the nginx access-proxy (https://github.com/mozilla-iam/testrp.security.allizom.org/tree/master/webserver_configurations/OpenID_Connect/Nginx) on top of the dashboard and use the headers, instead of flask-oidc.
This provides us with full session management/refresh and a separation layer between the application and the authentication + authorization.

Here's list of sub tasks that I know of:

- [ ] (S?) Implement a generic ansible container and upload it to the AWS containers repository
- [ ] (S) Derive an nginx access-proxy container from it, with the testrp setup from above
- [ ] (S?) modify sso-dashboard to use the HTTP headers instead of flask-oidc
- [ ] (S?) setup the deploy environment to enforce the usage of the access-proxy
- [ ] (S?) deploy sso-dashboard with access-proxy

Note: labelled as bug since not having session management is more of a bug for us

**Comment by dividehex** [comment]
This is no longer a goal.  We will continue to use Flask-pyoidc.
