### ISSUE TITLE
Unexpected "first time" message on okta?

### ISSUE THREAD

**Issue by groovecoder** [mozilla-iam/sso-dashboard#110]
Yesterday & today, when I tried to access phonebook, I was redirected to okta. When I entered my email address, it said it was the first time I had connected to okta from my browser, which is definitely not true.

Were cookies & sessions removed yesterday?

![image](https://cloud.githubusercontent.com/assets/71928/25662270/89627c6e-2fd9-11e7-80bb-d3e57ea47a6c.png)

**Comment by andrewkrug** [comment]
@groovecoder thanks for your question.  This would not have been a side effect of deploying this dashboard... necessarily.  However the old portal was also under the domain sso.mozilla.com and depending on how you got there previously it could be that your browser interpreted it to be a new session now that you're accessing at mozilla.okta.com.  If you'd like to feel free to post this question on Mozilla's discourse to see if anyone had the same issue.  We have a category just for the sso-dashboard.  https://discourse.mozilla-community.org/c/iam/dashboard
