### ISSUE TITLE
Truncate title length and add hover tool tip

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#116]
Reduced size of app-blocks has caused some grid breakdown due to longer title lengths.

Actions
- Truncate app titles via a max character length, example: `ASAP (AWS Secur...`
- Provide users with a tool tip on hover that provides full app name (similar to tool tip on search clear 'x').

![photo_2017-05-05_11-06-42](https://cloud.githubusercontent.com/assets/18686986/25758318/f3c4cc60-3182-11e7-8bf4-0d9f335e0656.jpg)

**Comment by comzeradd** [comment]
We could also just add a `max-width` to the app name to make sure it doesn't break the grid and it's fully visible.

![screen shot 2017-05-05 at 21 40 41-fullpage](https://cloud.githubusercontent.com/assets/939357/25759511/8700f230-31db-11e7-8254-672464906977.png)

**Comment by m-branson** [comment]
Yes, though adding vertical space doesn't help the grid either. :( Would like to move forward with truncating to condense information visually.

**Comment by andrewkrug** [comment]
I deployed the code that partially fixes this just now in pull #121

**Comment by andrewkrug** [comment]
We do truncate long names now.
