### ISSUE TITLE
Egencia login page is shown instead of mozilla okta login page

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/sso-dashboard#124]
This is happening on device only, I tried on devices with android and iOS operating systems. 
After login to sso dashboard and click Egencia app, I am redirected to Egencia login page instead of mozilla okta login page. 
See [video](https://drive.google.com/a/mozilla.com/file/d/0B23-kTHWDoXOTHNFNVpoYlBBYm8/view?usp=sharing).
 
CC: @andrewkrug

**Comment by dividehex** [comment]
Egencia is no longer available on this dashboard.
