### ISSUE TITLE
Implement low- and med-risk alert UI

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#130]
Based on scope decisions for initial release [(#96)](https://github.com/mozilla/iam-project-backlog/issues/96), low- and medium-risk alert UI is ready for implementation. Success messaging has been added as well.

- Visual annotation for spacing/sizing/styling can be found [here](https://drive.google.com/open?id=0B0vmiicLLrGuelZ0UEpweDZkS2M).
- Icons have been added [here](https://drive.google.com/open?id=0B0vmiicLLrGudnFnTkhHSExoNzg).

![low-risk](https://cloud.githubusercontent.com/assets/18686986/26085068/382376f2-3996-11e7-9280-edbfe3751610.png)

![medium-risk](https://cloud.githubusercontent.com/assets/18686986/26085070/3a63f89c-3996-11e7-8880-b4c80a50f4c4.png)

![success](https://cloud.githubusercontent.com/assets/18686986/26085071/3c0f948a-3996-11e7-9038-677cc5f50ad0.png)

**Comment by andrewkrug** [comment]
This has been implemented  and deployed in production @hmitsch @m-branson @comzeradd @gdestuynder thanks for all the hard work!

**Comment by hmitsch** [comment]
Congrats! 👍

**Comment by m-branson** [comment]
Fantastic, thanks @andrewkrug same to you!
