### ISSUE TITLE
YouTube embded on 404 does not honor DNT settings

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#132]
This was reported in a bugzilla bug as well.  On the 404 page the youtube video sends analytics to doubleclick.  

1. The way I see it we could have javascript that removes the video if DNT is set.
2. Do the same but also have JS inline a cute image.
3. Do away with the video all together and get open design to make us a 404 graphic.  

@hmitsch @comzeradd @m-branson Thoughts on this?

**Comment by hmitsch** [comment]
I thought we had wrapped the video inside a DNT container? That's what we had discussed. It is the way to do things according to our tracking guidelines on MANA.

This means, I am for option 1: Wrap the video inside a DNT container.
@comzeradd knows what I mean, he has done this before.

-Henrik

**Comment by andrewkrug** [comment]
Cool this is also in https://bugzilla.mozilla.org/show_bug.cgi?id=1369201

**Comment by comzeradd** [comment]
Wrapping the video on DNT is a bit more complicated. I open a [PR](https://github.com/mozilla-iam/sso-dashboard/pull/133) with a quick fix.
