### ISSUE TITLE
The dashboard tells me my firefox is out of date, when it's not

### ISSUE THREAD

**Issue by jdow** [mozilla-iam/sso-dashboard#173]
The line at https://github.com/mozilla-iam/sso-dashboard/blob/master/dashboard/models/alert.py#L163 is not working, likely because it can't compare two numbers that have two decimal places in them, i.e. "55.0.3"

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla-iam/sso-dashboard/pull/174

**Comment by andrewkrug** [comment]
Deployed in production
