### ISSUE TITLE
Nightly or Beta?

### ISSUE THREAD

**Issue by jabradford** [mozilla-iam/sso-dashboard#190]
https://github.com/mozilla-iam/sso-dashboard/blob/43cb946d29ce764ba9e0c9c18201fd6097c7c5cc/dashboard/templates/dashboard.html#L68

Since we are in entering the final push for 57, do we want to change this to Beta to increase the testing against that target or do we want to leave it at Nightly? @asadotzler Mark and Dave have differing views on this -care to weigh in?

**Comment by asadotzler** [comment]
I think it's more important to have people on Beta for the next month than
on Nightly.

- A

**Comment by hmitsch** [comment]
PR created: https://github.com/mozilla-iam/sso-dashboard/pull/191

**Comment by hmitsch** [comment]
PR for the Auth0 Lock created: https://github.com/mozilla-iam/auth0-deploy/pull/156

**Comment by hmitsch** [comment]
PR for our NDA Discourse: https://github.com/mozilla/discourse-mozilla-theme/pull/2

**Comment by andrewkrug** [comment]
This issue will close when #191 merges to production.

**Comment by andrewkrug** [comment]
This has been deployed.
