### ISSUE TITLE
Add IP to "unknown country" warning

### ISSUE THREAD

**Issue by edmorley** [mozilla-iam/sso-dashboard#192]
Upon visiting https://sso.mozilla.com/dashboard today I see a "Did you recently login from Unknown, Norway?" warning. Now I very much doubt this is a real problem (and is likely just a geolocation inaccuracy), but to confirm either way I really need to know the IP address.

As such, please can the warning be modified to show the IP?

**Comment by andrewkrug** [comment]
This alert data actually surfaces from code in MozDef that creates the end user alert.  https://github.com/mozilla/MozDef/blob/d89c0eb6d098cabd8869c3b94ecf52b5d7fe2fd8/alerts/plugins/sso_dashboard.py

I'd suggest adding this request there.

**Comment by edmorley** [comment]
Thank you, I've opened mozilla/MozDef#536.
