### ISSUE TITLE
Support secure, signed error msgs with fields for the forbidden page

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#196]
Ex:
https://sso.mozilla.com/forbidden?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJlcnJvcl9tZXNzYWdlIjoiWW91IG11c3Qgc2V0dXAgYSBzZWN1cml0eSBkZXZpY2UgKFwiTUZBXCIsIFwiMkZBXCIpIGZvciB5b3VyIEdpdEh1YiBhY2NvdW50IGluIG9yZGVyIHRvIGFjY2VzcyB0aGlzIHNlcnZpY2UuIFBsZWFzZSBmb2xsb3cgdGhlIDxhIGhyZWY9XCJodHRwczovL2hlbHAuZ2l0aHViLmNvbS9hcnRpY2xlcy9zZWN1cmluZy15b3VyLWFjY291bnQtd2l0aC10d28tZmFjdG9yLWF1dGhlbnRpY2F0aW9uLTJmYS9cIj4gR2l0SHViIGRvY3VtZW50YXRpb248L2E-IHRvIHNldHVwIHRoZSBkZXZpY2UgYW5kIHRyeSBsb2dnaW5nIGluIGFnYWluLiIsInJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vc29jaWFsLWxkYXAtcHdsZXNzLnRlc3RycC5zZWN1cml0eS5hbGxpem9tLm9yZy9yZWRpcmVjdF91cmkiLCJjbGllbnRfbmFtZSI6InNvY2lhbC1sZGFwLXB3bGVzcy50ZXN0cnAuc2VjdXJpdHkuYWxsaXpvbS5vcmciLCJjb25uZWN0aW9uIjoiZ2l0aHViIiwiaWF0IjoxNTA5NDA1NzgxLCJleHAiOjE1MDk0MDk0MTF9.jDJ86nGILNN9NOqWEhFBJvSda7Dl-d93U-Gz4DMWcDPdWe9KTDwqiRAV0AvFohB7csQzLJ35nmmuPU_SLdxEWvoYlPZipcGyK_SNcz2Tl9aGJ7CvPDspLySG_urSDtzsruP4e4ZjFM4KnSKTwTNes8_5BabTPvaLjKwG6UcU4XER0pvRK40wRVAb35_D0fvWDUVq4jC1cPl81FO8832D7kWdRiWro7Oyg4EQ3qBrBOA5fXmeLPPMfCNy5fW45jYJzLGTE1kMogQqRiAhCq_hdY0MGTnhPdELSHp74BJP9fxihsD4xTO56o_Tffigy9x_vJQkCj3QtmIaWSWGTjn2b6AOx3O7AGlME82m6oCbuL3QD5F0MBMwMfs7uGWAOZssJMcDrYunWpM6Hj74HHF-mTpWvxfwAp8AlSACf7YLgBoOpaVSqsg9Vq7269_HOAWWvKFg5JN_xmko5jTVbapEXjueKHV3Rlln5MlZ5sB26LC5DOuhngLuUIIXWyZcUBQZKuaxsFpc7WEADLgehxH3Tsm5D4WCL2KvzCP_8ifXHtuAyl_Zvg68L_KCW9ZYSOH8lhSbfMuYRyjTsNrxSLbgjpDzeYqvvvxkf0cWIvDL8e9K0EfedN6mD7rIrMI2YaT-zoH6VdiopaGrV8mlprYus5pTVe6e5uNg_na_R1wy8r4&state=8aSCbieYn6uJQXfPq5oDjmqLju8mK6cu

This is a JWT that is signed by auth0dev with:
```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAq+VUxlYiD5AuhhwkHDoy
aWWF3pYsBlFh9TzwYxcMGo6LWT89coLnP7VTyKlglNIfLnJd7jca9UBuB8HTPPaj
NHnNTiFyPFSn1hiXjH2byCC6p5fprEaDk5waZU580i4CiYXqkkYgUmuH5ou2yx5n
VBTbfr+rdT4kKQv/CzOYGZ7+NMUGWa3/5tLfIrEvgWkSLInzkUeXTKxnE+9kP/Sa
C8H6l6pJnoh9ZbcrxDhdmYzLLvsKHCkbvgBs3biAdHCsxqDxW1HiN32XxG8cZrsM
5ud7glsMceYZO6hCSen/rATZbdstDMcKkf310iPX1Eayg3Op3YRUSvLsVjynlPff
TRV1fChIiqpAggKlx1wjEI6QPnAgiSQ4XBpy1B+qTI9mwPapNrcb3nJE41MOGDdl
aKpyLxgZxB86cJa9UAvFHANGO3Ep5VgtR3hQ+jZF6DaGQ8c0srhx8178ubrlV64k
uq+Z3UFAdxClvSFw4x5rNmmWgS7o48or2xVuuW1414FXMPok+C5GZlgzdnsgw1ZT
hsMcetmmzkaQ9rylfauQGX32Negqe9arGEFmpjb2Tol4NMQ//734nTSvCYf/J4B/
tt62s9tAMMYvJo7FQWj4BK7uF/blSm73aEoVQb4wsZ2QYjLyYVphvPZkaWZdp4Z/
x4I9OOyNa8mhfd+xt9OnYusCAwEAAQ==
-----END PUBLIC KEY-----
```
we'll have a different public key for auth0 prod.

Decoded JWT:
### Header
```
{
  "typ": "JWT",
  "alg": "RS256"
}
```
### Payload
```
{
  "error_message": "You must setup a security device (\"MFA\", \"2FA\") for your GitHub account in order to access this service. Please follow the <a href=\"https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/\"> GitHub documentation</a> to setup the device and try logging in again.",
  "redirect_uri": "https://social-ldap-pwless.testrp.security.allizom.org/redirect_uri",
  "client_name": "social-ldap-pwless.testrp.security.allizom.org",
  "connection": "github",
  "iat": 1509405781,
  "exp": 1509409411
}
```

**Comment by gdestuynder** [comment]
Current error codes:

{
"githubrequiremfa": 'You must setup a security device (\"MFA\", \"2FA\") for your GitHub account in order to access this service. Please follow the <a href=\"https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/\"> GitHub documentation</a> to setup the device and try logging in again.',
"notingroup": "Sorry, you do not have access to relying party. Please consult <a href="mailto:eus@mozilla.com">eus@mozilla.com</a> if this is an error.",
"primarynotverified": "You primary email is not verified. Please verify your email with your identity provider in order to use this service.",
"incorrectaccount": "Sorry, you may not login with that login method. Please always login with LDAP instead, for that login name"
}

**Comment by gene1wood** [comment]
For `incorrectaccount` can you send an additional value like `preferred_connection` with the name of the connection that the user should be using since it won't always be LDAP?

**Comment by gdestuynder** [comment]
ok

**Comment by gene1wood** [comment]
What are the possible values for `connection` (e.g. `github`) so I can make a map between the values and the way they are presented (e.g. `github => GitHub`)?

Are `Mozilla-LDAP` and `Mozilla-LDAP-Dev` some of them?

**Comment by gene1wood** [comment]
Here's what I see so far in the UI
* `google-oauth2`
* `github`
* `Mozilla-LDAP-Dev`
* `email`

**Comment by gdestuynder** [comment]
correct - Mozilla-LDAP is for prod, Mozilla-LDAP-Dev for auth0 dev

**Comment by gdestuynder** [comment]
test link:

https://sso.allizom.org/forbidden?error=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjb2RlIjoiZ2l0aHVicmVxdWlyZW1mYSIsInJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vc29jaWFsLWxkYXAtcHdsZXNzLnRlc3RycC5zZWN1cml0eS5hbGxpem9tLm9yZy9yZWRpcmVjdF91cmkiLCJjbGllbnRfbmFtZSI6InNvY2lhbC1sZGFwLXB3bGVzcy50ZXN0cnAuc2VjdXJpdHkuYWxsaXpvbS5vcmciLCJjb25uZWN0aW9uIjoiZ2l0aHViIiwiaWF0IjoxNTA5NDc3NzAwLCJleHAiOjE1MDk0ODEzMzB9.gKABF8_4lAl2OWatLlInGg8Ia5CyANMLA-Ir12vuq8p--q4k92vbeiVnwJzX3ptDu0XF0ao0sFE7064kK29NEGkxXMtyQ4gt2ROkXhogzBs2jP6wFl7MAK9X-iDSg5avDpAivEG69jYoLy7dpnB4iofoEaU57AcSx2gGqMdQkoJ3KHgPvywDdDrZ-JhXIpiwsbTRJdKxo1MAthtGGdQNS6J0ZDoJAeP9wDeexgj87lzsQUwbacT96Ymnjk5uQqj3GbOhXuGjNuF6fqH-bvDlfB2SRiof77Ouc8IuRkfuGAq4ucEU6TdmqCQ1MW2ncy3d7HJitynI0gHKqElNPJi31f7HGfENxJwCK5pJIXHRbm-qnQU9MrLTEhbMWteymTqcO7lOw6Yef6UYS6gfy20nTqyfVduNag21Exxm9Kq3OcD_xSF6ELoyaFrpHafD9ygv5i6C32CKE5FIdRu4euSL4p5yFAoFJmBBz2haMpKH_pdI2bTM5ohNmyP4AQBz1RFuXJmp88lo7V4texJvkCfHQgawQCQOm6oZNH9AlfmBEc2P0aS64bBY6-vgWOrWGppsyHrih_2E5PQws2GcjgMdEx5X3Lb77ZwYg8YkVVTPEBAG5ggnchOp-8ARBDvY_9xy6re0wkzpOiPEn_Yu07040O8JZK5_CzgCeUa8FLbTAi8&state=yxuyE4Wi8pePlmUS4utpb2Xgg0kP1_sY
