### ISSUE TITLE
Support for ihavebeenpwned or similar API

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#2]
https://haveibeenpwned.com/
The goal is to indicate to the user if their email was in a recent breach. UX wise, we should only indicate this to the user once and remove the notification afterwards.

This may be part of a bigger notification system along the lines of:

1-user gets notification of an important security issue on login (whichever the issue is)
2-user get choice of "Alert security team" "That was me, ignore & remember" "Ignore this time"

I suspect we might be able to get UX help to design the feature - the above options are loosely inspired from what I've seen done in the past.

**Comment by dividehex** [comment]
The alert and notifications functionality has been removed and this feature is no longer needed.
