### ISSUE TITLE
forbidden page message verification not being called

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/sso-dashboard#201]
It looks like [message verification isn't being called](https://github.com/mozilla-iam/sso-dashboard/blob/ac2128862cfa7c5c02cbbb59a0de232f97c3714f/dashboard/app.py#L173) as it's just the function not a call to the function. Should probably change

    token_verifier.verify

to

    token_verifier.verify()

**Comment by andrewkrug** [comment]
verify is a property.

**Comment by gene1wood** [comment]
Ah got it, I didn't know about the `@property` decorator.
