### ISSUE TITLE
ESR incorrectly/unfairly flagged as older-than-stable

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/sso-dashboard#209]
Running latest ESR (gasp!) falls prey to simple greater-than/less-than logic in dashboard/models/alert.py : _firefox_out_of_date  and puts up a banner of "Your version of Firefox is older than the current stable release."

If you want to quibble that it IS older than stable, fine... but it flags me as being at 'Medium Risk' and links to a more-info that admonishes that I'm putting Moz at risk, which should be false for a fully patched ESR.

**Comment by andrewkrug** [comment]
@tristanweir can you weigh in on whether this should be a "medium" or "low"

**Comment by gene1wood** [comment]
This also affects all Ubuntu users as Ubuntu is always behind stable (as the packaging has to be completed). As a result, 100% of the time that I go to the dashboard I get this warning.

This causes [alarm fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue) for all ESR and Ubuntu users which is bad.

**Comment by andrewkrug** [comment]
I think we're doing to de-escalate all the browser alerts to low.  I'm open to a proposal on changing the code to reason about ESR.  Does anyone on this thread want to make a PR?

**Comment by gene1wood** [comment]
I'd argue that a constant alarm of any level including `LOW` is bad for the user and inures them to the alarms and causes them to ignore them. I know for myself, I don't even see the alarm line anymore because it's always present and inapplicable. Ubuntu or ESR users have no option to resolve the alarm. There's no action they can take in response to it, which is why I think we should seek to remove the alarm instead of changing the severity level shown in the alarm.

**Comment by andrewkrug** [comment]
@gene1wood see above comments regarding the problem with reasoning about ESR using only the user-agent string.  I'd love to be able to suppress this if we can find a way.

**Comment by andrewkrug** [comment]
closed by pr #334

**Comment by gene1wood** [comment]
#334 seems like a good quick stop gap for this but I worry we may have swung too far in the other direction.

By changing the alert to check for versions older than ESR, that solves the problem of both ESR and recent (within the last month) versions (like in Ubuntu) from showing false positives.

But it also results in, for example, someone running Firefox 53 from April 2017 not getting an alert.

Additionally, as of today there are now two versions of ESR, [52 and 60](https://www.mozilla.org/en-US/firefox/organizations/).

So warning users who are older than April 2017 is good, we probably want something that checks if the user is running either
* The major version of the newest version of ESR as of one month before now
* The major version of the newest version of legacy ESR as of one month before now
* The major version of Firefox as of one month before now

This would result in
* Users running the newest ESR 60.0.1 not getting a notification
* Users running ESR 60.0.0 that was current within the last month not getting a notification
* Users running the newest Firefox Stable 62.0.0 not getting a notification
* Users running Firefox Stable 61.0.1 that was current within the last month not getting a notification
* Users running Firefox Stable 59.0.0 from March 13, 2018 would get a notification

**Comment by dividehex** [comment]
The alerts and notifications functionality has been removed from the dashboard entirely.  This will not be an issue again.
