### ISSUE TITLE
Clarify the "Sorry, you may not login using X" error message

### ISSUE THREAD

**Issue by edmorley** [mozilla-iam/sso-dashboard#213]
Treeherder is in the process of switching SSO from https://login.taskcluster.net to using Auth0 directly. 

The former [is excluded](https://github.com/mozilla-iam/auth0-deploy/blob/c8279ad577bebb37ca9d7f7bef10e8eedd6c0def/rules/force-users-login-most-secure-method.js#L7) from the "force users to login with the most secure method" feature, whereas the latter is not. As such after the switch, some existing users will now see the enforcement message for the first time. 

Example:

![image](https://user-images.githubusercontent.com/501702/35677882-360bf71e-0749-11e8-9994-30946375e254.png)

We're glad this enforcement is taking place - and had hoped that the error message would be clear enough for them - however after trialling the new implementation several users were confused and thought not being able to log in via their old (less secure) method was a bug rather than intentional.

I think it might help if the message wording was changed from:

> Sorry, you may not login using GitHub.
> Please instead always login with LDAP.

To something like:

> Sorry, you may not login using GitHub.
> We require login to be performed using the most secure 
> method available for your account, which is LDAP.

It may also be worth adding a link to a wiki/mana/FAQ page with an explanation and the list of which logins are preferred over others.

The relevant code is here:
https://github.com/mozilla-iam/sso-dashboard/blob/b4c1ad60c5a53b8386739fb218967ae3fb24d493/dashboard/auth.py#L147-L148

Many thanks :-)

**Comment by hmitsch** [comment]
@andrewkrug do we already have a PivotalTracker issue for this? Either way, I'd scope it into the next sprint (starting tomorrow). Ok?

**Comment by hmitsch** [comment]
@m-branson, what do you think about the proposed wording change? It looks great to me.

Proposal:
> Sorry, you may not login using GitHub.
> We require login to be performed using the most secure
> method available for your account, which is LDAP.

**Comment by m-branson** [comment]
@hmitsch looks great, super helpful edit @edmorley -- appreciate it!

**Comment by hmitsch** [comment]
This is in production now. :-)

![screen shot 2018-03-17 at 21 07 45](https://user-images.githubusercontent.com/869692/37559512-e6b0b45a-2a27-11e8-9159-fdd71c7bbde4.png)

**Comment by edmorley** [comment]
Many thanks!
