### ISSUE TITLE
Gravatar image broken

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/sso-dashboard#226]
When I browse to the SSO dashboard my gravatar neither shows my image, nor the gravatar default avatar, nor the mozillians default avatar.

The link points to

```
https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=300x300&r=pg&d=https%3A%2F%2Fcdn.mozillians.org%2Fmedia%2Fimg%2Fdefault_avatar.png
```

which redirects to

```
https://i0.wp.com/cdn.mozillians.org/media/img/default_avatar.png?ssl=1
```

Here's a screenshot showing the broken image

[![screenshot](https://screenshotscdn.firefoxusercontent.com/images/12da30aa-69ee-4097-b7d7-c088e679b192.png)](https://screenshots.firefox.com/1tVIc3oKYkVYjIuz/sso.mozilla.com)

**Comment by andrewkrug** [comment]
@gene1wood this is in scope for the current sprint.  Expect an update in the next week or two!

**Comment by andrewkrug** [comment]
We dropped support for the mozillians API.  Please let me know if this is still broken.

**Comment by gene1wood** [comment]
This appears fixed for me. Thanks!
