### ISSUE TITLE
The last two apps are not sorted correctly

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/sso-dashboard#236]
Most of the apps listed are alphabetized, but the final two apps in the grid are sorted incorrectly to the end rather than being amidst their sorted peers.

**Comment by andrewkrug** [comment]
Not sure why this is happening but the requisite code is here:

**Comment by globau** [comment]
```
self.apps['apps'] = sorted(
    self.apps['apps'], key=operator.itemgetter('name')
)
```

this should be:

```
apps['apps'].sort(key=lambda a: a['application']['name'].lower())
```

**Comment by globau** [comment]
the current code throws `KeyError` on the lookup of `name`; that try/catch block is doing more harm than good imho.
