### ISSUE TITLE
Give ability to drag and drop apps into a specific order and hide/show apps

### ISSUE THREAD

**Issue by jdow** [mozilla-iam/sso-dashboard#24]
I think users might like to have their apps in a specific order, like an order in which they use them the most. In addition, there are likely to be some apps that a user would never want to use, or just not enough to want to have to look at it every day. Perhaps a drag and drop / pinning thing for the icons so that a user can shuffle them around to whatever order they want, but also be able to just click something to hide the app permanently, with a link somewhere at the bottom that says "Show hidden apps" that could be pressed to access one of the hidden apps if needed, or to restore it to the dashboard.

**Comment by dividehex** [comment]
This feature is no longer being targeted.
