### ISSUE TITLE
Hilight/Notify on a new app being added to a user's dashboard

### ISSUE THREAD

**Issue by jdow** [mozilla-iam/sso-dashboard#25]
The old dashboard has a feature for when a user's app list changes between site visits, it will pop out a little notification letting the user know that they now have access to a new app, and that app is hilighted a bit on the dashboard so that they can find it easily. It might be something to consider once we have a notification console and the ability to interact with app icon placement and show/hide abilities.

**Comment by dividehex** [comment]
The alert and notifications functionality has been removed and this feature is no longer needed.
