### ISSUE TITLE
Doing page refresh on sso.mozilla.com increases the number of alerts

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard#252]
STR:
1. Login to sso.mozilla.com in Firefox 58.0.2 (59 is latest version) -> "Your version of Firefox is older than the current stable release." alert is shown.
2. Click refresh button in the browser.

Expected:
Page remains the same as before the page refresh.

Actual:
2 alerts for the firefox version being old are shown on the page. If doing page refresh again, another alert is shown. 

![alerts](https://user-images.githubusercontent.com/5293100/37527417-ac3de786-293a-11e8-92bf-a829b43670b3.png)

**Comment by andrewkrug** [comment]
This is the code that ensures that this alert and others like it are not duplicated.  https://github.com/mozilla-iam/sso-dashboard/blob/master/dashboard/models/alert.py#L113

**Comment by andrewkrug** [comment]
fixed in sso.allizom.org let me know if you agree.
