### ISSUE TITLE
Update Expensify logo size to 80px max-width

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#271]
Expensify logo is currently at 120x120 pixel image size and should be reduced to 80px max width (80x80 square) within the app-logo block.

FYI the 120x120 pixel image size is an artifact of initial implementation. @hidde wondering if we can work together to fix the CSS on these images (feel free to break out as a separate task if needed). I believe the logos themselves were originally exported with padding built in 😬 (this was a design file execution, never meant to be replicated in CSS). Ideally the text based logos (e.g. moderator, phonebook, etc) would be implemented as text with a max width and the icon based logos as images. 

See app-icons without padding [here](https://drive.google.com/drive/folders/1cbpGQxw6dLlREJhmcaQwz9XKZCeO3Joo?usp=sharing).

![expensify-logo-size](https://user-images.githubusercontent.com/18686986/38439279-eabf3e4e-3991-11e8-89fe-cfb6ff7e5095.png)

cc @hmitsch @andrewkrug

**Comment by m-branson** [comment]
@hidde the icons themselves have been exported at 160 width to help account for retina implementation (see g-drive folder for icons). This should help with your proposed solution, which is inline with my ideal implementation strategy. 👍

Let me know if you run into issues with the text based implementation, happy to help with visual QA to ensure we have consistency.

**Comment by hidde** [comment]
The Expensify logo is now updated and live.
