### ISSUE TITLE
500 error on /logout if no flask session is present

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#289]
visit https://sso.mozilla.com/logout => get 500 error if there is no session cookie with sso.mozilla.com

this happens if you hit "logout" from many properties as this is where the universal logout sends you back to (granted that this is supported by the RP). For example, Gapps logout will send you there - and if you haven't logged into the sso dashboard very recently you'll get a 500 error

**Comment by dividehex** [comment]
This was issue was resolved awhile back with an updated to the Flask-pyoidc lib.
