### ISSUE TITLE
"Escalate to Security" button shown for medium risk alerts

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard#294]
If I login to sso.allizom.org in an older FF version, I get the "Your version of Firefox is older than the current stable release" alert, which currently has the option to Escalate to Security. I don't believe we want to show this button for medium risk alerts. @andrewkrug , thoughts?

![escalate](https://user-images.githubusercontent.com/5293100/40295209-2de72ce6-5ce1-11e8-9956-4b33f23a3caf.png)

**Comment by andrewkrug** [comment]
Fixed
