### ISSUE TITLE
Sso dashboard

### ISSUE THREAD

**Issue by syam3526** [mozilla-iam/sso-dashboard#301]
Something wrong with the sso dashboard.
It's not responsive in Mobile view. 
The navbar cuts off in Mobile view.

**Comment by viorelaioia** [comment]
Hi Syam!
Thanks for reporting this. I would need a bit more info in order to investigate this.
Can you please tell me what device are you using and maybe add a few more details on the issue you are seeing, so that I can try and reproduce it? 
Thanks!

**Comment by viorelaioia** [comment]
After discussion on slack, the issue @syam3526 was seeing is the scrolling happening when navbar is opened, which makes the page look bad when scrolling down to the footer. 
@syam3526 , there is a ticket opened for this a while ago, which contains a bit more info: https://github.com/mozilla-iam/sso-dashboard/issues/131 
I will close this one as it is a duplicate and we will use that ticket for tracking progress. We will try to get it fixed next sprint.
Thanks!
