### ISSUE TITLE
mozillians SSO

### ISSUE THREAD

**Issue by syam3526** [mozilla-iam/sso-dashboard#307]
Tried to login using my google provider  linked with mozillians profile and got this error. 

![bug1](https://user-images.githubusercontent.com/11440246/40576895-10b0efb6-611b-11e8-9300-335e5b120a34.png)

Its okay if there is only i cardview but having soo many cards and the asking to file a bug deep down is too much. 
Refer the screenshot for details.

**Comment by syam3526** [comment]
but on the top its showing my name. as if i am already logged in

**Comment by andrewkrug** [comment]
This is an issue for mozilla/mozillians not sso.mozilla.com.  Please file that there.
