### ISSUE TITLE
Jump page is not the same as current okta dashboard - things missing

### ISSUE THREAD

**Issue by Phrozyn** [mozilla-iam/sso-dashboard#32]
![screenshot 2017-03-27 12 00 35](https://cloud.githubusercontent.com/assets/4267984/24368336/a73ff416-12e5-11e7-9a52-ea43dfe0e274.png)
![screenshot 2017-03-27 12 00 57](https://cloud.githubusercontent.com/assets/4267984/24368340/a9d6a224-12e5-11e7-9de1-628cd177cffa.png)

**Comment by andrewkrug** [comment]
This is the dashboard if you sign in with anything besides LDAP.  This issue will close when Mozilla implements account linking of some form in auth0

**Comment by dividehex** [comment]
This is no longer relevant.
