### ISSUE TITLE
This repository is missing a GitHub pull requests template.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/sso-dashboard#321]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

I recently discovered in #319 that this repository has extra requirements for pull requests that are not currently documented in a pull request template. Please create one.

**Comment by andrewkrug** [comment]
Thanks for the feedback and your contributions to the dashboard @floatingatoll a pull request template has been added to the repo.
