### ISSUE TITLE
Add confirmation button to the geo location alert

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/sso-dashboard#324]
Currently when a user gets the Geo location alert, if they accidentally click the wrong button, it pages the infosec on call. Please add a confirmation where the user has to click a second time to prevent accidental clicks. It's probably worth indicating in this confirmation dialog that this will page the infosec on call and they will contact you, the user.

[Related PagerDuty event](https://mozilla.pagerduty.com/incidents/PWM11IV)

**Comment by dividehex** [comment]
Alerts and notification functionality has been removed from the dashboard.
