### ISSUE TITLE
Notify user if their device is configured in an undesirable way

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#33]
Based on new functionality in the Duo admin API.

As a user I should receive notification if my device for DUO diverges from security best practice.

- Is the device encrypted y/n
- Is the device protected by screen lock
- Have SMS Passcodes been sent to this phone
- If SMS Recommend DUO app
- Is the DUO app out of date on the user device.

**Comment by jeffbryner** [comment]
I'd re-cast this as a something like: 

Gather stats on how well our end-user population is doing as it relates to software updates. 

DUO performs this today based on some combination of visibility via their phone app and via the browser interaction with their site. I'd bet we could get to this info via browser headers.

**Comment by dividehex** [comment]
The alert and notifications functionality has been removed and this feature is no longer needed.
