### ISSUE TITLE
Inescapapable Notifications

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/sso-dashboard#333]
Land on dashboard using ESR, which gives a notification ala #209 .  Click 'more info'.
Read silly alert.  Click 'dismiss'.  Notification disappears.
Item 1: There's no link to go back to the beginning except the upper left 'home' button.  Maybe that's intentional.  but it's a blank screen otherwise.
Item 2: There's still a red '1' on this screen, and going back to the home screen, the silly alert about my browser is still there.  So, I haven't really dismissed anything.

**Comment by andrewkrug** [comment]
I'm suggesting to the rest of the team that we lower the alerting threshold to be ESR as a desired baseline.  If browser < ESR current version then alert.  

This is the only way to really handle this since ESR doesn't identify itself in the header.
