### ISSUE TITLE
Deal with Observatory Report

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#35]
Finally got a scan of this site from observatory cli.

```
{
    "scan": {
        "grade": "D-",
        "likelihood_indicator": "MEDIUM",
        "response_headers": {
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "Content-Encoding": "gzip",
            "Content-Type": "text/html; charset=utf-8",
            "Date": "Tue, 28 Mar 2017 19:03:51 GMT",
            "Keep-Alive": "timeout=100",
            "Strict-Transport-Security": "max-age=15724800",
            "Transfer-Encoding": "chunked",
            "Vary": "Accept-Encoding",
            "X-Robots-Tag": "noindex, nofollow, nosnippet, noarchive",
            "set-cookie": "_csrf=; Path=/"
        },
        "score": 25,
        "tests_failed": 6,
        "tests_passed": 6,
        "tests_quantity": 12
    },
    "tests": {
        "content-security-policy": {
            "data": null,
            "expectation": "csp-implemented-with-no-unsafe",
            "pass": false,
            "result": "csp-not-implemented",
            "score_description": "Content Security Policy (CSP) header not implemented",
            "score_modifier": -25
        },
        "contribute": {
            "data": null,
            "expectation": "contribute-json-only-required-on-mozilla-properties",
            "pass": true,
            "result": "contribute-json-only-required-on-mozilla-properties",
            "score_description": "Contribute.json isn't required on websites that don't belong to Mozilla",
            "score_modifier": 0
        },
        "cookies": {
            "data": {
                "_csrf": {
                    "domain": "auth-dev.mozilla.auth0.com",
                    "expires": null,
                    "httponly": false,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": false
                },
                "auth0": {
                    "domain": "auth-dev.mozilla.auth0.com",
                    "expires": 1490987031,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "auth0-mf": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "session": {
                    "domain": ".sso.allizom.org",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": false
                }
            },
            "expectation": "cookies-secure-with-httponly-sessions",
            "pass": false,
            "result": "cookies-session-without-secure-flag-but-protected-by-hsts",
            "score_description": "Session cookie set without the Secure flag, but transmission over HTTP prevented by HSTS",
            "score_modifier": -10
        },
        "cross-origin-resource-sharing": {
            "data": {
                "acao": null,
                "clientaccesspolicy": null,
                "crossdomain": null
            },
            "expectation": "cross-origin-resource-sharing-not-implemented",
            "pass": true,
            "result": "cross-origin-resource-sharing-not-implemented",
            "score_description": "Content is not visible via cross-origin resource sharing (CORS) files or headers",
            "score_modifier": 0
        },
        "public-key-pinning": {
            "data": null,
            "expectation": "hpkp-not-implemented",
            "includeSubDomains": false,
            "max-age": null,
            "numPins": null,
            "pass": true,
            "preloaded": false,
            "result": "hpkp-not-implemented",
            "score_description": "HTTP Public Key Pinning (HPKP) header not implemented",
            "score_modifier": 0
        },
        "redirection": {
            "destination": "https://auth-dev.mozilla.auth0.com/login?client=mc1l0G4sJI2eQfdWxqgVNcRAD9EAgHib&protocol=oauth2&state=kaezYvz5bMALRJKO&redirect_uri=https%3A%2F%2Fsso.allizom.org%2Fredirect_uri&nonce=oDujcM94JuySXlRF&response_type=code&scope=openid",
            "expectation": "redirection-to-https",
            "pass": true,
            "redirects": true,
            "result": "redirection-to-https",
            "route": [
                "http://sso.allizom.org/dashboard",
                "https://sso.allizom.org/dashboard",
                "https://auth-dev.mozilla.auth0.com/authorize?nonce=oDujcM94JuySXlRF&state=kaezYvz5bMALRJKO&redirect_uri=https%3A%2F%2Fsso.allizom.org%2Fredirect_uri&response_type=code&client_id=mc1l0G4sJI2eQfdWxqgVNcRAD9EAgHib&scope=openid",
                "https://auth-dev.mozilla.auth0.com/login?client=mc1l0G4sJI2eQfdWxqgVNcRAD9EAgHib&protocol=oauth2&state=kaezYvz5bMALRJKO&redirect_uri=https%3A%2F%2Fsso.allizom.org%2Fredirect_uri&nonce=oDujcM94JuySXlRF&response_type=code&scope=openid"
            ],
            "score_description": "Initial redirection is to https on same host, final destination is https",
            "score_modifier": 0,
            "status_code": 200
        },
        "referrer-policy": {
            "data": null,
            "expectation": "referrer-policy-private",
            "pass": true,
            "result": "referrer-policy-not-implemented",
            "score_description": "Referrer-Policy header not implemented",
            "score_modifier": 0
        },
        "strict-transport-security": {
            "data": "max-age=15724800",
            "expectation": "hsts-implemented-max-age-at-least-six-months",
            "includeSubDomains": false,
            "max-age": 15724800,
            "pass": true,
            "preload": false,
            "preloaded": false,
            "result": "hsts-implemented-max-age-at-least-six-months",
            "score_description": "HTTP Strict Transport Security (HSTS) header set to a minimum of six months (15768000)",
            "score_modifier": 0
        },
        "subresource-integrity": {
            "data": {
                "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js": {
                    "crossorigin": null,
                    "integrity": null
                }
            },
            "expectation": "sri-implemented-and-external-scripts-loaded-securely",
            "pass": false,
            "result": "sri-not-implemented-but-external-scripts-loaded-securely",
            "score_description": "Subresource Integrity (SRI) not implemented, but all external scripts are loaded over https",
            "score_modifier": -5
        },
        "x-content-type-options": {
            "data": null,
            "expectation": "x-content-type-options-nosniff",
            "pass": false,
            "result": "x-content-type-options-not-implemented",
            "score_description": "X-Content-Type-Options header not implemented",
            "score_modifier": -5
        },
        "x-frame-options": {
            "data": null,
            "expectation": "x-frame-options-sameorigin-or-deny",
            "pass": false,
            "result": "x-frame-options-not-implemented",
            "score_description": "X-Frame-Options (XFO) header not implemented",
            "score_modifier": -20
        },
        "x-xss-protection": {
            "data": null,
            "expectation": "x-xss-protection-1-mode-block",
            "pass": false,
            "result": "x-xss-protection-not-implemented",
            "score_description": "X-XSS-Protection header not implemented",
            "score_modifier": -10
        }
    }
}
```

**Comment by andrewkrug** [comment]
Updated observatory report... let's get this to a "B" or better prior to go live 

`{
    "scan": {
        "grade": "C-",
        "likelihood_indicator": "MEDIUM",
        "response_headers": {
            "Connection": "keep-alive",
            "Content-Length": "12110",
            "Content-Security-Policy": "script-src ajax.googleapis.com 'self' fonts.googleapis.com https://*.google-analytics.com; img-src *.wp.com 'self' https://mozillians.org https://*.google-analytics.com; report-uri /csp_report; default-src 'self'; style-src 'self' fonts.googleapis.com ajax.googleapis.com; font-src fonts.gstatic.com 'self' fonts.googleapis.com",
            "Content-Type": "text/html; charset=utf-8",
            "Date": "Wed, 26 Apr 2017 21:48:53 GMT",
            "Public-Key-Pins": "includeSubDomains; report-uri=/hpkp_report; max-age=5184000",
            "Server": "gunicorn/19.6.0",
            "Set-Cookie": "session=.eJyVVWuP2jgU_StVpPbTAEkgwwwS2h0KgckMmSEPB7JaIcc2YOLEaZwwQNv_XpuHuu1W-5AQsu_DPr73npPP2rIgZQZzkldaryprcqNBhIgQy4qnJNd6mpU4exTcD4zxxnpoP221G43iq_ezjC5l0Kaqil6rJdCGZFA0eUFyips5qVoFLEir4IwiSkTL1PVuS79tZTWraGMFUcVLeSDM5CF_aNkKan_KXY1PO2QwfdwRzqNJZisc7T-tgYu8h-H96GE9oYkKJftC6xmd-7bZvesaloQGq4uhY54NQlzwCQkQ1tWmgcmumfEjZQw2lUFvIp61JIyc54jI6O2nifCRf0hfF92gG2TSJepEOiD-Mj0nNp6HD6-NIdl9gWlZr7Wv36uy3L5VqjLvVEY8Z0_TMVjMIvYKw-IZbG0Phvuhn22oZ7pFYLInH4BbP7BfYMit5wxYfj7YTnXj5EtM7zHM8ZZk92YwdMbTyJvEbQ96xuIQjPU9zkCVTFzq6cCIwCaaju3RbA7i6ZbpwYQ5SGd1sLVjGKamHxljaMb2dB6zJNofFym2se3ZYeqA2dG2I7aBLzab4wlLgcI2cp_g2JuHZ-x6NC_GSDfsxVHimwyegsiIQlZUIdswfxTXIBMGZKD0UvAKQPwx2g44slnhz10nAQt9obuOmxphGACXpOkx0L0tGVkBNtkG6Is3Pyp2cj-C7cKFzLaCvLCnl1pFIybrsT_CyJlH2cZJhoPj6T2ZW_hB7CTR-i0ebQZuurde5kU8zTZiwfCYpPvqZY4hOIK3KJ0aGBSLcB5vPT1uR2xqYfPxQCYDGb8Xi3baIaExmgXulKSjQzB83E8jR9Z_MAVGwaPA9bG6T70nAOYiM16SEfuUSPxJGjuLo-whC4_JxAFeJo4glZWInMDfpvXsYJiyfgBusUdk1eO5u0ABGL5EGCbs3granuXpuHyeOzNsgxEKvI9uEN-Gs35fDVctSEnzFVeDhRiVdH0cyvH6V47caKgksCJ4qYihmbrRbehmw7AC47Zn3UuqNDuWEcs4rMieQcr6p4n-_coQyY0b3lf_GPUvRhlOVKiixM_BV99yJxGvKMFXXTlZhWL233MklVcwo-ywzGGmKPikSHWjrelOEupie8hxSd6UteR1cTrpMa9KKV5VRFMqHX4FKzGEYpNwWGJpKDY8Jwnn6fKsaqoevCwauyKXS_m_VNvLEuKMKnMlO0JgvVQ1FxcfJisoNUvdQVBd0urwIEQt70bkpRAEqTQCsyW_bFTOab2Uz5TJV3_GEVcKWiLEeK0g8rSCS6V856Qdkr0lpcSVCy5hXGErH6FiKQWLZ7CiPFdFo1hG00pKq6yGnAye5wSdnD3tZ6VS1wqfIwpl31aQCdmTouQ7eUZ50jbtPGZLin-RfdU5eelJvC_aLXuAa66g_NCkd5f-5RSlv3Twcg1zejw9JMxpJf7X8BUUVXVJ_iLsorku4Q5WsDyJ-XnZgsmq072_xbALoX6HLQtbEjc2zISYyEz030S_c6d_KPvF-gPun8563354b9ryh3D-_esg9-cjhVqlzSJf_4ePgqxngX8mX6dh3gam0Wvf9QyzqXdu4x_q_g-fmK_fAKZ9lP0.C-KnRQ.WuL1g6dfuM_Px-VXKHET_tFQK-0; Domain=.sso.allizom.org; Expires=Wed, 26-Apr-2017 22:03:53 GMT; HttpOnly; Path=/",
            "Strict-Transport-Security": "includeSubDomains; max-age=1",
            "X-Content-Type-Options": "nosniff",
            "X-Download-Options": "noopen",
            "X-Frame-Options": "sameorigin",
            "X-Permitted-Cross-Domain-Policies": "none",
            "X-XSS-Protection": "1; mode=block"
        },
        "score": 45,
        "tests_failed": 4,
        "tests_passed": 8,
        "tests_quantity": 12
    },
    "tests": {
        "content-security-policy": {
            "data": {
                "default-src": [
                    "'self'"
                ],
                "font-src": [
                    "fonts.gstatic.com",
                    "'self'",
                    "fonts.googleapis.com"
                ],
                "img-src": [
                    "*.wp.com",
                    "'self'",
                    "https://mozillians.org",
                    "https://*.google-analytics.com"
                ],
                "object-src": [
                    "'self'"
                ],
                "report-uri": [
                    "/csp_report"
                ],
                "script-src": [
                    "ajax.googleapis.com",
                    "'self'",
                    "fonts.googleapis.com",
                    "https://*.google-analytics.com"
                ],
                "style-src": [
                    "'self'",
                    "fonts.googleapis.com",
                    "ajax.googleapis.com"
                ]
            },
            "expectation": "csp-implemented-with-no-unsafe",
            "pass": true,
            "result": "csp-implemented-with-no-unsafe",
            "score_description": "Content Security Policy (CSP) implemented without 'unsafe-inline' or 'unsafe-eval'",
            "score_modifier": 5
        },
        "contribute": {
            "data": null,
            "expectation": "contribute-json-with-required-keys",
            "pass": false,
            "result": "contribute-json-not-implemented",
            "score_description": "Contribute.json file missing from root of website",
            "score_modifier": -5
        },
        "cookies": {
            "data": {
                "_csrf": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "auth0": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "auth0-mf": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "session": {
                    "domain": ".sso.allizom.org",
                    "expires": 1493244236,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": false
                }
            },
            "expectation": "cookies-secure-with-httponly-sessions",
            "pass": false,
            "result": "cookies-session-without-secure-flag",
            "score_description": "Session cookie set without using the Secure flag or set over http",
            "score_modifier": -40
        },
        "cross-origin-resource-sharing": {
            "data": {
                "acao": null,
                "clientaccesspolicy": null,
                "crossdomain": null
            },
            "expectation": "cross-origin-resource-sharing-not-implemented",
            "pass": true,
            "result": "cross-origin-resource-sharing-not-implemented",
            "score_description": "Content is not visible via cross-origin resource sharing (CORS) files or headers",
            "score_modifier": 0
        },
        "public-key-pinning": {
            "data": "includeSubDomains; report-uri=/hpkp_report; max-age=5184000",
            "expectation": "hpkp-not-implemented",
            "includeSubDomains": true,
            "max-age": 5184000,
            "numPins": 0,
            "pass": false,
            "preloaded": false,
            "result": "hpkp-header-invalid",
            "score_description": "HTTP Public Key Pinning (HPKP) header cannot be recognized",
            "score_modifier": -5
        },
        "redirection": {
            "destination": "https://sso.allizom.org/dashboard",
            "expectation": "redirection-to-https",
            "pass": true,
            "redirects": true,
            "result": "redirection-to-https",
            "route": [
                "http://sso.allizom.org/dashboard",
                "https://sso.allizom.org/dashboard"
            ],
            "score_description": "Initial redirection is to https on same host, final destination is https",
            "score_modifier": 0,
            "status_code": 200
        },
        "referrer-policy": {
            "data": null,
            "expectation": "referrer-policy-private",
            "pass": true,
            "result": "referrer-policy-not-implemented",
            "score_description": "Referrer-Policy header not implemented",
            "score_modifier": 0
        },
        "strict-transport-security": {
            "data": "includeSubDomains; max-age=1",
            "expectation": "hsts-implemented-max-age-at-least-six-months",
            "includeSubDomains": true,
            "max-age": 1,
            "pass": false,
            "preload": false,
            "preloaded": false,
            "result": "hsts-implemented-max-age-less-than-six-months",
            "score_description": "HTTP Strict Transport Security (HSTS) header set to less than six months (15768000)",
            "score_modifier": -10
        },
        "subresource-integrity": {
            "data": {},
            "expectation": "sri-implemented-and-external-scripts-loaded-securely",
            "pass": true,
            "result": "sri-not-implemented-but-all-scripts-loaded-from-secure-origin",
            "score_description": "Subresource Integrity (SRI) not implemented, but all scripts are loaded from a similar origin",
            "score_modifier": 0
        },
        "x-content-type-options": {
            "data": "nosniff",
            "expectation": "x-content-type-options-nosniff",
            "pass": true,
            "result": "x-content-type-options-nosniff",
            "score_description": "X-Content-Type-Options header set to \"nosniff\"",
            "score_modifier": 0
        },
        "x-frame-options": {
            "data": "sameorigin",
            "expectation": "x-frame-options-sameorigin-or-deny",
            "pass": true,
            "result": "x-frame-options-sameorigin-or-deny",
            "score_description": "X-Frame-Options (XFO) header set to SAMEORIGIN or DENY",
            "score_modifier": 0
        },
        "x-xss-protection": {
            "data": "1; mode=block",
            "expectation": "x-xss-protection-1-mode-block",
            "pass": true,
            "result": "x-xss-protection-enabled-mode-block",
            "score_description": "X-XSS-Protection header set to \"1; mode=block\"",
            "score_modifier": 0
        }
    }
}`

**Comment by andrewkrug** [comment]
@comzeradd how many of these can we just "take care" of.  Where are the quick wins?

**Comment by andrewkrug** [comment]
Ok I got this to an "A"  @hmitsch @comzeradd @tyearns assuming that means we can close this one. 
```
{
    "scan": {
        "grade": "A",
        "likelihood_indicator": "LOW",
        "response_headers": {
            "Connection": "keep-alive",
            "Content-Length": "12105",
            "Content-Security-Policy": "script-src ajax.googleapis.com 'self' fonts.googleapis.com https://*.google-analytics.com; img-src *.wp.com 'self' https://mozillians.org https://*.google-analytics.com; report-uri /csp_report; default-src 'self'; style-src 'self' fonts.googleapis.com ajax.googleapis.com; font-src fonts.gstatic.com 'self' fonts.googleapis.com",
            "Content-Type": "text/html; charset=utf-8",
            "Date": "Thu, 27 Apr 2017 00:53:48 GMT",
            "Public-Key-Pins": "pin-sha256=lQH28uKDTqXDlj2rAY3rYWqOqZi/L2wM0l/AOxt+Fbk=; pin-sha256=LyE9nDS269hk1SrbGY0KvuQIsuF5lpob7NIu4vOOZho=; includeSubDomains; report-uri=/hpkp_report; max-age=5184000",
            "Server": "gunicorn/19.6.0",
            "Set-Cookie": "session=.eJyVVPtv4jgQ_ldWkXZ_ApoEQlskdNceBPoIbQNxIKdT5NgGTBw7jR1K2d3__Wwe2tu91T2kKLLnm5dnvpnPVlqSqoCccGX1VFWThgURIlKmSuSEWz3rFtV8UjrtxOtM5SuCVsOi-Ix-tmCNrd7vVoEcZo868v7OJS9LHO9eV2CCwpvB9fBmNaaZ9UfDIrvS6jmd67Z7dd3pdLUfqE4Cr30USKkjrpUqZe_iAtZq3cRk2yrEnjIGW0Zgt5AoLnQSXHBEtHaXv0u4CoeLAIO6u3jSkKwzDUD8JTgaNh8HN8_NAdl-gXlVr6yv356Qbt6UecYHY5HM2UMwAouXmD3DqHwEGz-E0W4wLdY0dCflzGUPUwC605n_BCPhPRbAm_LbTWA7Byxzw7uI4w0prt3Z4H4UxOE4aYcwdBbvs5G9wwVQ2XhCQxs4MVjHwcgfvsxBEmyYPRuze2SzerbxExjl7jR2RtBN_GCesCze7Rc59rEf-lF-D172vh-zNXzy2RyPWQ5MbsPJAxyF8-iYux3PyxGyHX-x1_mNbx9msRNHrFQRW7PpMKlBIR3IQBXm4BmA5Ld4cyuQz8rpfHKfgYW9sCf3k9yJohmYkDy3Z04YBkOvxC5bA3vxNo3LLRl6Q9guJ9pPd5ZrPNe14oAGG_AaM2PPXmMOWDz0RLzxH0KGQRCrOGPRO3CiDoyT8HHDeMT88WPkvE5AchvtdY3j8PnFYQ4eeU4wv32GIyfJ9qGHil0QRKw9ccsqGKO-aWQtSUX5UpgmIkY1j-8GupX_yseGhSoCFcGpIaHl2s5l03abjjdzuj3vWtOy1fGcROthMwUFpKx_YM-vZzZqHjZE3_wx6p-EWp0YVUO_H5XPWLrVGS8pweeBO0ilmaK_2-ixWcKCsveUw8LQ_cEQuGGt6FaT9yS74bgib0Zaibo8eLrjqtJTrWKaUw1MFVRyAOU6E7DCWlCuBSeZEHl6HHdTD1GVzW3J9VH_U3M9HSEuqBErmDEC69TUXJ4wTJawZsrEIKiuqHq_kbLWsRF5KiVBxozAIhWni7E5nFP9TG18xguBhFktFUJM1CZFkSuYFkt4Mtoi3VtS6by4FDqNc9oGI1SmejmIAioquCkaxVqbKkpMNTQzBOcEHcCe9eNWMGHlVCAKdd-WkEndk7ISW-2jOuwR60izlOKfWJ93ig5a6ELQJURKVKYHuBYmle-a9OHUP05R_lNAVCvI6f7wkIhTJf8X-UqKVF2RvyxR2VpVcAsVrA6L83i8gNmyc3ndxfASQvsKex72dN7YcTPiIjezf5H9zpX9qeqXq0-4f_D1sX3z0fX1hzD_ton1_ehSmlPeKvnqPyxgXc8S_zh8naZ7ObPtXvuy53qty243-a7u_7DOv_4JWRpGSg.C-LSnA.9hhg8h-JPThHC94Km4StyCoPkss; Domain=.sso.allizom.org; Expires=Thu, 27-Apr-2017 01:08:48 GMT; HttpOnly; Path=/",
            "Strict-Transport-Security": "includeSubDomains; max-age=15768000",
            "X-Content-Type-Options": "nosniff",
            "X-Download-Options": "noopen",
            "X-Frame-Options": "sameorigin",
            "X-Permitted-Cross-Domain-Policies": "none",
            "X-XSS-Protection": "1; mode=block"
        },
        "score": 95,
        "tests_failed": 2,
        "tests_passed": 10,
        "tests_quantity": 12
    },
    "tests": {
        "content-security-policy": {
            "data": {
                "default-src": [
                    "'self'"
                ],
                "font-src": [
                    "fonts.gstatic.com",
                    "'self'",
                    "fonts.googleapis.com"
                ],
                "img-src": [
                    "*.wp.com",
                    "'self'",
                    "https://mozillians.org",
                    "https://*.google-analytics.com"
                ],
                "object-src": [
                    "'self'"
                ],
                "report-uri": [
                    "/csp_report"
                ],
                "script-src": [
                    "ajax.googleapis.com",
                    "'self'",
                    "fonts.googleapis.com",
                    "https://*.google-analytics.com"
                ],
                "style-src": [
                    "'self'",
                    "fonts.googleapis.com",
                    "ajax.googleapis.com"
                ]
            },
            "expectation": "csp-implemented-with-no-unsafe",
            "pass": true,
            "result": "csp-implemented-with-no-unsafe",
            "score_description": "Content Security Policy (CSP) implemented without 'unsafe-inline' or 'unsafe-eval'",
            "score_modifier": 5
        },
        "contribute": {
            "data": {
                "description": "Mozilla Single SignOn Dashboard for Auth0",
                "name": "sso-dashboard"
            },
            "expectation": "contribute-json-with-required-keys",
            "pass": false,
            "result": "contribute-json-missing-required-keys",
            "score_description": "Contribute.json exists, but is missing some of the required keys",
            "score_modifier": -5
        },
        "cookies": {
            "data": {
                "_csrf": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "auth0": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "auth0-mf": {
                    "domain": "",
                    "expires": null,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": true
                },
                "session": {
                    "domain": ".sso.allizom.org",
                    "expires": 1493255331,
                    "httponly": true,
                    "max-age": null,
                    "path": "/",
                    "port": null,
                    "secure": false
                }
            },
            "expectation": "cookies-secure-with-httponly-sessions",
            "pass": false,
            "result": "cookies-session-without-secure-flag-but-protected-by-hsts",
            "score_description": "Session cookie set without the Secure flag, but transmission over HTTP prevented by HSTS",
            "score_modifier": -10
        },
        "cross-origin-resource-sharing": {
            "data": {
                "acao": null,
                "clientaccesspolicy": null,
                "crossdomain": null
            },
            "expectation": "cross-origin-resource-sharing-not-implemented",
            "pass": true,
            "result": "cross-origin-resource-sharing-not-implemented",
            "score_description": "Content is not visible via cross-origin resource sharing (CORS) files or headers",
            "score_modifier": 0
        },
        "public-key-pinning": {
            "data": "pin-sha256=lQH28uKDTqXDlj2rAY3rYWqOqZi/L2wM0l/AOxt+Fbk=; pin-sha256=LyE9nDS269hk1SrbGY0KvuQIsuF5lpob7NIu4vOOZho=; includeSubDomains; report-uri=/hpkp_report; max-age=5184000",
            "expectation": "hpkp-not-implemented",
            "includeSubDomains": true,
            "max-age": 5184000,
            "numPins": 2,
            "pass": true,
            "preloaded": false,
            "result": "hpkp-implemented-max-age-at-least-fifteen-days",
            "score_description": "HTTP Public Key Pinning (HPKP) header set to a minimum of 15 days (1296000)",
            "score_modifier": 5
        },
        "redirection": {
            "destination": "https://sso.allizom.org/dashboard",
            "expectation": "redirection-to-https",
            "pass": true,
            "redirects": true,
            "result": "redirection-to-https",
            "route": [
                "http://sso.allizom.org/dashboard",
                "https://sso.allizom.org/dashboard"
            ],
            "score_description": "Initial redirection is to https on same host, final destination is https",
            "score_modifier": 0,
            "status_code": 200
        },
        "referrer-policy": {
            "data": null,
            "expectation": "referrer-policy-private",
            "pass": true,
            "result": "referrer-policy-not-implemented",
            "score_description": "Referrer-Policy header not implemented",
            "score_modifier": 0
        },
        "strict-transport-security": {
            "data": "includeSubDomains; max-age=15768000",
            "expectation": "hsts-implemented-max-age-at-least-six-months",
            "includeSubDomains": true,
            "max-age": 15768000,
            "pass": true,
            "preload": false,
            "preloaded": false,
            "result": "hsts-implemented-max-age-at-least-six-months",
            "score_description": "HTTP Strict Transport Security (HSTS) header set to a minimum of six months (15768000)",
            "score_modifier": 0
        },
        "subresource-integrity": {
            "data": {},
            "expectation": "sri-implemented-and-external-scripts-loaded-securely",
            "pass": true,
            "result": "sri-not-implemented-but-all-scripts-loaded-from-secure-origin",
            "score_description": "Subresource Integrity (SRI) not implemented, but all scripts are loaded from a similar origin",
            "score_modifier": 0
        },
        "x-content-type-options": {
            "data": "nosniff",
            "expectation": "x-content-type-options-nosniff",
            "pass": true,
            "result": "x-content-type-options-nosniff",
            "score_description": "X-Content-Type-Options header set to \"nosniff\"",
            "score_modifier": 0
        },
        "x-frame-options": {
            "data": "sameorigin",
            "expectation": "x-frame-options-sameorigin-or-deny",
            "pass": true,
            "result": "x-frame-options-sameorigin-or-deny",
            "score_description": "X-Frame-Options (XFO) header set to SAMEORIGIN or DENY",
            "score_modifier": 0
        },
        "x-xss-protection": {
            "data": "1; mode=block",
            "expectation": "x-xss-protection-1-mode-block",
            "pass": true,
            "result": "x-xss-protection-enabled-mode-block",
            "score_description": "X-XSS-Protection header set to \"1; mode=block\"",
            "score_modifier": 0
        }
    }
}
```

**Comment by andrewkrug** [comment]
Getting the cert pins was the hardest part.  I used this command to get them from amazon acm: 

```
openssl s_client -connect sso-d-appli-14pg36if1ak1c-83690096.us-west-2.elb.amazonaws.com:443 | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
```

**Comment by hmitsch** [comment]
Congrats @andrewkrug !!!
