### ISSUE TITLE
Update dashboard favicon to 'grid' icon

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/sso-dashboard#354]
@hidde until we can work with brand on custom icons for our IAM properties, @hmitsch and I would like to move forward with assigning this grid icon for the SSO Dashboard.

<img width="152" alt="screen shot 2018-12-14 at 5 12 34 pm" src="https://user-images.githubusercontent.com/18686986/50037169-774c6100-ffc3-11e8-9e0b-627eca37768e.png">

See Zeplin [here](https://app.zeplin.io/project/5a4ed39f5dac041b0d390e41/dashboard?seid=5c14523871324f509cf74594) and the feather icon set API is [here](https://github.com/feathericons/feather).

**Note that I'm having some issues exporting SVG assets to Zeplin, let me know if you encounter any issues.

**Comment by gene1wood** [comment]
@andrewkrug What day do you want to release this? I ask so I know what day to release #283

**Comment by gene1wood** [comment]
Whoops, that question I asked was meant for the PR not the issue that PR fixes, disregard (I've re-asked the question in the PR)
