### ISSUE TITLE
common url endpoints

### ISSUE THREAD

**Issue by jeffbryner** [mozilla-iam/sso-dashboard#37]
Historically some folks don't use the dashboard, or use common urls like https://sso.mozilla.org/workday in emails. 

Ideally the dashboard handles these legacy links by either: 

1) Rerouting to the home page to display apps (or search)
2) Preserves the link and acts as a shortcut to the app. 

URLs I'm aware of include https://mana.mozilla.org/wiki/display/SD/SSO+Quick+Links

**Comment by andrewkrug** [comment]
@jeffbryner thanks for filing.  I also want to point out that these are also called "vanity" urls by some folks.  This will likely end up being implemented in a nginx redirects for certain paths.  Thanks for capturing.

**Comment by andrewkrug** [comment]
Cross link: https://github.com/mozilla/iam-project-backlog/issues/84
