### ISSUE TITLE
Logout from SSO dashboard returns error page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard#393]
**STR:**

1. Login to sso.mozilla.com with either a staff or a contributor account
2. Click user avatar, the logout button

**Expected:**
SSO login page is returned 

**Actual:**
Error page is returned

![Screen Shot 2019-08-05 at 12 04 27](https://user-images.githubusercontent.com/5293100/62459586-70f43a80-b788-11e9-9ccc-405d74ae6bf1.png)

**Comment by ioana-chiorean** [comment]
I was reproducing these too, also withe enable/disable autologin option

**Comment by viorelaioia** [comment]
This error page is also displayed when navigating to Enable / Disable Auto-login page from the sso dashboard user menu. 
@kangsterizer , @andrewkrug , can you please take a look over this issue? Thanks!

**Comment by gdestuynder** [comment]
looks like an auth0 issue with the new universal login
i turned that feature off, which fixes the issue for now
