### ISSUE TITLE
Add Matrix to Dashboard

### ISSUE THREAD

**Issue by satdav** [mozilla-iam/sso-dashboard#410]
Since Matrix is now replacing IRC can we add that on the dashboard it uses the Auth0 Login what most Mozilla sites use

**Comment by gene1wood** [comment]
@satdav Feel free to request this in github.com/mozilla-iam/sso-dashboard-configuration . Having this set to not display in the SSO Dashboard was requested in mozilla-iam/sso-dashboard-configuration#319
