### ISSUE TITLE
Change Flask server configuration to avoid redirecting to http

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/sso-dashboard#414]
As mentioned in #391 the Flask server is configured currently to redirect to http. Please update this to redirect to https.

**Comment by andrewkrug** [comment]
Should be settable as an environment variable on the pod if memory serves.  There's also a ingress controller for the pod where you could handle a rewrite.

**Comment by The-smooth-operator** [comment]
@gene1wood do you want me to look into this? I can play with environment variables and/or ingress controller settings in stage and come back with PR for staging and later prod.

**Comment by The-smooth-operator** [comment]
After a bit of research, I found out that forcing Flask to use https when `redirect()` is not possible via setting an environment variable.
This behavior and other nice security additions are normally achieved by using [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman). See references [1] and [2].

Other option would be modify the kubernetes ingress rule to redirect the path `/` to `/dashboard`, like this the application won't have to do the redirection. This is less intrussive but it feels like the app should be able to handle this, and not leave the responsability to the layer in front of it.

[1] flask security guide https://flask.palletsprojects.com/en/1.1.x/security/
[2] related SO post https://stackoverflow.com/questions/32237379/python-flask-redirect-to-https-from-http/50041843

**Comment by andrewkrug** [comment]
As an FYI the app already has flash-talisman in it.  https://github.com/mozilla-iam/sso-dashboard/blob/f6977858ca3c196a74555881032afde00586dd6f/dashboard/app.py#L17

**Comment by floatingatoll** [comment]
Closed by #437.
