### ISSUE TITLE
Implement User Menu for Initial Release

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#42]
@m-branson commented on [Fri Apr 21 2017](https://github.com/mozilla-iam/sso-dashboard-configuration/issues/3)

User menu functionality required for release:

1. User name visible on active menu
2. Log Out functionality available via active menu
3. If no gravatar available for a user, utilize the user icon from the designs.

**Comment by m-branson** [comment]
Adding #66 here as it falls under the same scope.

Assigning this to @comzeradd :)

**Comment by m-branson** [comment]
@comzeradd here is element style annotation for the desktop menu. :) 
Mobile utilizes same sizing/styling, though spacing is slightly different because the mobile app-bar is `height: 80px` vs. desktop app-bar `height: 70px` and we're providing more room for tap vs. click. Will post those here later today.

**Sizing:**

![element-sizing](https://cloud.githubusercontent.com/assets/18686986/25452112/4ee5a184-2a79-11e7-8ae7-15da66e233d4.png)

**Spacing:**

![element-spacing](https://cloud.githubusercontent.com/assets/18686986/25452120/5489deac-2a79-11e7-9d25-29bca3251074.png)

**Text:**

![menu-text-style](https://cloud.githubusercontent.com/assets/18686986/25452129/5d535ca2-2a79-11e7-9205-28d8c1cb05f1.png)

**Border:**

![border-style](https://cloud.githubusercontent.com/assets/18686986/25452141/61ed9f0c-2a79-11e7-8b35-8e691289e12c.png)

**Comment by comzeradd** [comment]
@m-branson can you also help me with the [mobile screen](https://drive.google.com/drive/folders/0B0vmiicLLrGuWkl1ajZ2d0JtZG8)? Let's account two viewport widths here. Highend smartphones (360px) and lowend (320px).

**Comment by m-branson** [comment]
Ah yes, thanks for the reminder! This to-do got lost in my list yesterday. Will post today. :)

**Comment by m-branson** [comment]
@comzeradd here is mobile spacing & text styling including the 'coming soon' for a 375px wide viewport (iphone 7). Icons (including the gravatar) are the same size as desktop. This should get you started, will post a 320px wide viewport by end of day PST. 👍 

**Overview:**

![mobile-menu-coming-soon](https://cloud.githubusercontent.com/assets/18686986/25542017/b3d4b462-2c05-11e7-8bb2-3515c66f27ee.png)

**Spacing:**

![mobile-menu-coming-soon-spacing](https://cloud.githubusercontent.com/assets/18686986/25541982/8ee49ece-2c05-11e7-83f6-af260dd12aef.png)

**Styling:**

![mobile-menu-coming-soon-styles](https://cloud.githubusercontent.com/assets/18686986/25541988/9a361c9e-2c05-11e7-8738-723e57f3965d.png)

**App-bar for reference:**

![mobile-app-bar-padding](https://cloud.githubusercontent.com/assets/18686986/25542056/d3786d2c-2c05-11e7-9317-14f817fb7ce1.png)

![mobile-app-bar-sizes](https://cloud.githubusercontent.com/assets/18686986/25542065/d7ac4d3c-2c05-11e7-9d3d-b39df234fb19.png)

**Comment by comzeradd** [comment]
Thanks @m-branson 👍 I'm not sure if the menu is going to fit on a 320px viewport, for lowend smarphones. Any suggestion for that case? Should we adjust the menu somehow?

**Comment by m-branson** [comment]
Yeah, I'm thinking the menu portion (below the app-bar) will go full viewport width on those smaller screen sizes. Like I said above, will be able to get you a 320px width version by end of day PST. 👍

**Comment by m-branson** [comment]
@comzeradd here's a 320px width mobile menu. I'm breaking the user name to two lines in this view, is that possible on your end? Sizes and styles are the same, spacing is only slightly different, see below. :)

**320px menu overview:**

<img width="372" alt="320px-mobile-menu" src="https://cloud.githubusercontent.com/assets/18686986/25549161/294393fc-2c25-11e7-84b2-811f25447af8.png">

**Spacing:**

<img width="438" alt="320px-mobile-menu-spacing" src="https://cloud.githubusercontent.com/assets/18686986/25549162/2943c034-2c25-11e7-8cef-a188d3305898.png">
