### ISSUE TITLE
Update ALL App Icons

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#43]
@comzeradd app icons have been updated and added to the [drive folder](https://drive.google.com/drive/folders/0B0vmiicLLrGuU1BNVTg0aWtLMkU?usp=sharing). **Please update ALL icons** as there have been some universal changes that affected sizing for those already migrated.

Please reach out with questions, thanks!

**Comment by comzeradd** [comment]
[PR opened](https://github.com/mozilla-iam/sso-dashboard-configuration/pull/6)

**Comment by m-branson** [comment]
@comzeradd possible to assign this to yourself and track as it is implemented? Thank you :)

**Comment by m-branson** [comment]
@comzeradd looks like phonebook, mana, mdc and the hub didn't get updated? During my last design update of the icons their type sizes changed. Now all of the wordmark placeholders should be the same size, though it looks like those four are still the older, larger versions.

**Comment by comzeradd** [comment]
Yes, good catch. New PR already merged. All app icons should be updated now.

**Comment by m-branson** [comment]
Awesome! Thanks @comzeradd
