### ISSUE TITLE
UI : App bar (header) updates

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#51]
@comzeradd let's increase the height of the search container to 40px. This allows for consistent usability (click or tap) across viewports.

Also, please increase the container size of the user gravatar to 40px square and remove the 5px of padding around the image. When the user gravatar is in place it can fill the 40px square without padding or borders.

Logo height does not need to change, its size is plenty large enough. 👍

**Comment by m-branson** [comment]
Reopening as we aren't quite there yet with this update (please [bear with me](https://www.englishforums.com/English/BearBareWithMe/vclxd/post.htm) as I pixel push 😬).

@comzeradd here are some annotated components to help with sizing and padding, can align with these?

Desktop padding:

![app-bar-padding](https://cloud.githubusercontent.com/assets/18686986/25400567/e030efea-29a7-11e7-8ffb-830f748ebbf7.png)

Desktop element sizes:

![app-bar-sizes](https://cloud.githubusercontent.com/assets/18686986/25400571/e294afba-29a7-11e7-9e28-d8ede5b26d6a.png)

Mobile padding:

![mobile-app-bar-padding](https://cloud.githubusercontent.com/assets/18686986/25401028/586bb368-29a9-11e7-8c13-106f58f4e1c5.png)

Mobile element sizes:

![mobile-app-bar-sizes](https://cloud.githubusercontent.com/assets/18686986/25401034/5ee1d6f0-29a9-11e7-9b36-61b471e10e33.png)

**Comment by comzeradd** [comment]
Thanks for the detailed paddings :D Can you clarify also the spacing on the avatar? What size do we want the avatar and padding from its border.

**Comment by m-branson** [comment]
No problem, should have sent those through earlier. Or we can look into getting you a Sketch license so you can dig into the file a bit. :)

**Avatar with photo:** 
- 40px x 40px square size, no border.
- (desktop) 15px padding on all sides
- (mobile) 20px padding on all sides
- If you want desktop/mobile to be uniform padding, we can simply increase the desktop app-bar height by 10px to 80px total. :)

**Avatar without photo (icon default):**
![icon-avatar-size](https://cloud.githubusercontent.com/assets/18686986/25447293/7a0b081e-2a69-11e7-933e-db342c82b5e2.png)

![icon-avatar-padding](https://cloud.githubusercontent.com/assets/18686986/25447292/7a09d61a-2a69-11e7-803d-e5bba539614d.png)

**Comment by comzeradd** [comment]
I pushed a fix on 7361e67570abfd40e83bfa4a36d002dd02f76f15.

@m-branson could you check the current state on stage and see if all paddings are right now?

**Comment by m-branson** [comment]
So great! Nice work @comzeradd 👍
