### ISSUE TITLE
Focus search field when the dashboard load

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#60]
ie focus on <input name="filter" id="filter" placeholder="Search for an app by name" class="mui--is-empty mui--is-untouched mui--is-pristine" type="text"> when page loads

This allow for directly typing the app you want to log into

cc @m-branson since it's UX, feel free to close if it's invalid/on purpose/etc

**Comment by m-branson** [comment]
From a UX stand point I'm absolutely good with this. We have many different user types and I think we should accommodate those who are ultra keyboard savvy + help educate those who mouse-centric. :)

@comzeradd when the search field is focused we should be sure to keep the 'Search for an app by name' copy in view. 👍 

I'll tag this in the search UI #36 as well.

**Comment by comzeradd** [comment]
I guess we need that only for the Desktop view. On mobile, search is hidden by default and poping-up the keyboard right away can be irritating :D

**Comment by m-branson** [comment]
Yes, agreed desktop only. :)

**Comment by comzeradd** [comment]
Fixed at 26372bae18f2e0df75ee1b39c5259a814e32a844
