### ISSUE TITLE
Consider adding static files from https://github.com/mozilla/sso-mozilla-com

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#61]
I suspect at least https://github.com/mozilla/sso-mozilla-com/blob/master/signout.html is in use and we should keep that functionality

There's also a bunch of static files in /media.

cc @fox2mike

**Comment by andrewkrug** [comment]
@m-branson @comzeradd is the "signout" landing page in scope for the initial deployment.  I would assume so.  Let's try and replicate the current signout page at a flask route.  I'll take care of hooking up the backend parts if we can get it to look the right way.

**Comment by andrewkrug** [comment]
I've opened bug https://bugzilla.mozilla.org/show_bug.cgi?id=1352267 to get a copy of the access logs.  From there we can see if the content is still in use.

**Comment by fox2mike** [comment]
Yeah, @gdestuynder is correct here. We use that signout link explicitly in at least one place (mana) and a few others. @jdow might have an idea of other places it's being used at.

**Comment by m-branson** [comment]
@andrewkrug Yep, seems like it should be there. Good call.

To be clear, we're referencing [this](https://sso.mozilla.com/signout.html) though without the call to action for SSO sign out (as users are signing out of SSO).

**Comment by m-branson** [comment]
Went ahead and comp'd these. Let me know thoughts.

**Log out success screen:**

Includes a button to return to log in. @comzeradd this button would fill black on hover. 

![sso-logout](https://cloud.githubusercontent.com/assets/18686986/25363762/fce7e4b8-2911-11e7-93c5-353c71f6e432.jpg)

**Log in screen:** 

Auth0 lock within the Mozilla branded SSO header, sign up language removed. @comzeradd this button would fill #FABA00 (orange) on hover.

![sso-login](https://cloud.githubusercontent.com/assets/18686986/25363773/1da5992a-2912-11e7-814b-ae9fe6cd77f4.jpg)

**Comment by comzeradd** [comment]
I think we don't need a Login landing page. My understanding is that the SSO Dashboard redirects you to auth0 if you are not logged in.

**Comment by andrewkrug** [comment]
@comzeradd logout is minimum viable.  Also annoyingly it should respond to /logout.html as well as /logout because that's the way the apps are linked currently.

**Comment by m-branson** [comment]
> I think we don't need a Login landing page. My understanding is that the SSO Dashboard redirects you to auth0 if you are not logged in.

@comzeradd @andrewkrug @gdestuynder @gene1wood @akatsoulas @johngian : Apologies for the mass callout, but for the Auth0 Lock I want to understand the log in page behavior a bit better. I'm currently under the impression that we will be hosting the Auth0 Lock within the front-end of whichever site/RP it is being called from. Is this correct? If not, is this possible?

In the case of the sso dashboard, if a user wants to log in and navigates to sso.mozilla.org, I'm assuming they will see a log in page that looks something like this:

![sso-login](https://cloud.githubusercontent.com/assets/18686986/25397105/f4b6c3a6-299b-11e7-94b1-4c87e27ef391.jpg)

Whereas if that user were to navigate to Mozillians.org (while logged out) and selected log in / sign up they would receive a page that looks like this:

![landing](https://cloud.githubusercontent.com/assets/18686986/25397091/e721f4cc-299b-11e7-9f38-0e398ab176fa.jpg)

For both entities the Auth0 Lock is the user's Mozilla branded log in mechanism, but it is tailored to the site within which it is currently being viewed. (e.g., SSO dashboard doesn't need sign up language and utilizes orange accent color UI; Mozillians has sign up language and uses blue accent UI.)

**Comment by andrewkrug** [comment]
@m-branson this would be great to clarify at the tech / alignment.  The answer is all the things you described are possible.  However, most mozilla RPs will use "the one" hosted lock and likely not host their own.

**Comment by andrewkrug** [comment]
For sso-dashboard specifically it redirects to the hosted lock.

**Comment by m-branson** [comment]
Thanks @andrewkrug good to know. I do believe that the ParSys entities will be moving toward hosting their own, maybe?... And yes, agreed that it's a good tech alignment convo to have. 👍

**Comment by andrewkrug** [comment]
Let's identify the specific questions we'd like to answer around this and get them in the meeting notes ahead of time.  It should hopefully be a quick conversation around when to do host-lock vs self-hosted.  I think depending on implementation the hosted lock should be sufficiently parameter-ize-able and I like the idea of the lock effectively being/having a "brand identity".

**Comment by m-branson** [comment]
Okay, I think your note pretty much sums it up for the meeting notes, have [added](https://docs.google.com/a/mozilla.com/document/d/1Jos5Dqt2tH5S-hQYQKSx1To0AowPBPX5PkKmjlftgJg/edit?usp=sharing) for 4/27.

**Comment by m-branson** [comment]
Host-lock vs self-hosted conversation has been moved to next tech alignment meeting, 5/4...[added to the agenda](https://docs.google.com/a/mozilla.com/document/d/1Jos5Dqt2tH5S-hQYQKSx1To0AowPBPX5PkKmjlftgJg/edit?usp=sharing).

**Comment by andrewkrug** [comment]
@comzeradd @hmitsch this has to be in the initial deploy to replicate current functionality.  Must respond to /signout.html or there will be a lot of 404s. This could block our launch if not complete @jeffbryner

**Comment by m-branson** [comment]
Currently this screen can achieve this functionality (I believe):

![sso-logout](https://cloud.githubusercontent.com/assets/18686986/25550849/a9cac62e-2c31-11e7-8b77-0a96712af2d7.jpg)

This is where the Auth0 Lock UI refresh is headed, so would be a step in a forward direction.

**Comment by andrewkrug** [comment]
Does that screen live as html or jinja yet somewhere?  I might have to try and make something on Monday as a stand-in.

**Comment by m-branson** [comment]
Sadly, no. It lives as a static design file. 👎 (this is why I'm currently taking a web dev course on the side 😉 )

**Comment by jeffbryner** [comment]
If we can rough in something (just to avoid 404s), I think that works. I do not believe it is a widely used feature.

**Comment by andrewkrug** [comment]
This is satisfactory to launch. Closing.
