### ISSUE TITLE
UI : Footer Icon/Text Spacing

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/sso-dashboard#64]
Increase spacing between icons and their labels to 10px.

![footer-icon-spacing](https://cloud.githubusercontent.com/assets/18686986/25402340/4310f006-29ad-11e7-892a-2ec057797ddd.png)

**Comment by comzeradd** [comment]
This is also fixed at 7361e67570abfd40e83bfa4a36d002dd02f76f15
