### ISSUE TITLE
Assign Status Labels to New & Existing SSO-Dashboard Issues

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/sso-dashboard#65]
Team,

I have created status labels for the issues within this repo. Please do take a moment to assign the appropriate label to each of the stories as this helps with visibly tracking our progress within this repo.

**Comment by m-branson** [comment]
UX/UI issues updated.

**Comment by comzeradd** [comment]
I'll added all remaining issues to backlog. I'll defer to @andrewkrug if some of those are actually in progress.
