### ISSUE TITLE
Funfacts: Add a daily message in the top

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/sso-dashboard#67]
As a user of the SSO dashboaed I am presented with a fun fact/snipped/quote of the day upon opening to the dashboard in order to love the dashboard a little more every day.

**Comment by m-branson** [comment]
+1 to this idea, nice idea @hmitsch 👍 

Do you have a first quote I can use to mock something up for @comzeradd?

**Comment by comzeradd** [comment]
You can use a funfact from mozillians.org.

eg.
`588 Mozillians are web developers`

And we should think if we want to add a link there. Maybe with a icon? I'm thinking something similar to Firefox snippets that you can on `about:home`.

**Comment by m-branson** [comment]
@hmitsch @comzeradd here is an initial iteration of the fun fact styling, thoughts?

If there is time to implement, here is the styling info. The icon has been added to the [drive asset folder](https://drive.google.com/open?id=0B0vmiicLLrGuek9qLXdjWUhOQ0k) as well.

**Overview:**

![fun-fact](https://cloud.githubusercontent.com/assets/18686986/25591462/794a2b54-2e69-11e7-8398-d27c7e82db84.png)


**Spacing:**

![fun-fact-spacing](https://cloud.githubusercontent.com/assets/18686986/25591464/7c95e8f2-2e69-11e7-8e83-c548e7bcacc7.png)


**Sizing:**

![fun-fact-sizing](https://cloud.githubusercontent.com/assets/18686986/25591467/7fc10d04-2e69-11e7-9629-d1b67c2010e6.png)


**Styling:**

![fun-fact-styles](https://cloud.githubusercontent.com/assets/18686986/25591469/82e3e6f0-2e69-11e7-96c5-81f8af39f614.png)

**Comment by dividehex** [comment]
The alert and notifications functionality has been removed and this feature is no longer needed.
