### ISSUE TITLE
Google Analytics: Events all over the place

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/sso-dashboard#68]
* Events showing which applications are launched
* Events for clicks on the footer
* Events for clicks on the user menu

**Comment by andrewkrug** [comment]
@hmitsch can we put this in for the initial release?  I'd like this data from day 1.

**Comment by m-branson** [comment]
I second that request. Let's figure out what our users are actually using! ;)

**Comment by andrewkrug** [comment]
I am seeing events coming in.  So I'm going to close this issue out.
