### ISSUE TITLE
Broken link to sso-dashboard-configuration in README

### ISSUE THREAD

**Issue by edmorley** [mozilla-iam/sso-dashboard#73]
Not exactly urgent, but I spotted that the README says:

> In order to add applications to the dashboard there is an apps.yml file and a logos directory that exists in the Mozilla github org. For confidentiality this file is currently private. Though if you are interested in the dashboard you may CI this file and the images however you elect. Here at Mozilla we probably use CodePipeline to do that ;)
> 
> https://github.com/mozilla/sso-dashboard-configuration (Private repo for inside)

...however this repo appears to (a) now be located at https://github.com/mozilla-iam/sso-dashboard-configuration instead, (b) no longer be private (so the warning can be removed).

Many thanks!

**Comment by andrewkrug** [comment]
Thanks for the heads up @edmorley .
