### ISSUE TITLE
thinksmart asks me to login twice

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/sso-dashboard#96]
Repro:

* ensure you are LOGGED OUT of thinksmart
* login to the sso dashboard
* click on thinksmart

get prompted for login twice, instead of once.

notes: thinksmart uses SAML but seems to eventually redirect to OIDC on their side. It might be better if we natively did OIDC auth instead of SAML (?)

**Comment by jdow** [comment]
I e-mailed the SSO guy at Thinksmart for guidance here, but received an auto-reply that he's PTO until next week. When I had talked to him about it before, he said it is something he can fix on the thinksmart side. The other workaround would be to add a relayState parameter to our login URL, but he said it would be cleaner for him to fix, so let's wait on that.

**Comment by jdow** [comment]
The Thinksmart SAML guy and I worked to add a relay state parameter on both the dashboard URL and the thinksmart backend, so that either SP- or IDP-initiated SSO should now work without the login loop
