### ISSUE TITLE
dashboard shouldn't show services that i don't have access to (plansource)

### ISSUE THREAD

**Issue by globau** [mozilla-iam/sso-dashboard#99]
the new sso dashboard lists plansource which i don't appear to have access to (i guess it's US only?).

"Employee is not found by subscriber code 'bjones@mozilla.com'."

the dashboard shouldn't list items that i cannot access.

**Comment by andrewkrug** [comment]
@globau we currently don't have a us-employees group to filter on.  We soon will and then you'll see these apps disappear from your list.

**Comment by andrewkrug** [comment]
I'm going to close this issue here can you move it to sso-dashboard-configuration?  This is where group issues get tracked.

**Comment by globau** [comment]
created https://github.com/mozilla-iam/sso-dashboard-configuration/issues/21
